name: test terraform
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
  terraform:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: "3.69.0"
  tfinit:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: init terraform
        id: init
        run: terraform init
      - name: fmt terraform
        id: fmt
        run: terraform fmt
  tfplan:
    needs: tfinit
    runs-on: ubuntu-latest
    steps:
      - name: tf plan
        id: plan
        run: terraform plan
